train_data = [
    ("There is a cow in the field", {"entities": [(11, 14, "ANIMAL")]}),
    ("The picture shows a dog", {"entities": [(19, 22, "ANIMAL")]}),
    ("I saw a cat sleeping on the sofa", {"entities": [(8, 11, "ANIMAL")]}),
    ("A chicken is laying eggs in the barn", {"entities": [(2, 9, "ANIMAL")]}),
    ("The butterfly landed on the flower", {"entities": [(4, 13, "ANIMAL")]}),
    ("An elephant is walking in the zoo", {"entities": [(3, 11, "ANIMAL")]}),
    ("The horse runs across the meadow", {"entities": [(4, 9, "ANIMAL")]}),
    ("I found a spider on the wall", {"entities": [(10, 16, "ANIMAL")]}),
    ("A squirrel climbed up the tree", {"entities": [(2, 9, "ANIMAL")]}),
    ("There is a cat and a dog in the garden", {"entities": [(11, 14, "ANIMAL"), (19, 22, "ANIMAL")]}),
    
    ("Look at the cow grazing", {"entities": [(12, 15, "ANIMAL")]}),
    ("A dog is barking loudly", {"entities": [(2, 5, "ANIMAL")]}),
    ("The cat jumped on the table", {"entities": [(4, 7, "ANIMAL")]}),
    ("I have a chicken in my backyard", {"entities": [(9, 16, "ANIMAL")]}),
    ("The butterfly is very colorful", {"entities": [(4, 13, "ANIMAL")]}),
    ("Elephant ears are huge", {"entities": [(0, 8, "ANIMAL")]}),
    ("The horse is eating hay", {"entities": [(4, 9, "ANIMAL")]}),
    ("A spider weaved its web", {"entities": [(2, 8, "ANIMAL")]}),
    ("Squirrel is hiding nuts", {"entities": [(0, 7, "ANIMAL")]}),
    ("Cow and horse are in the field", {"entities": [(0, 3, "ANIMAL"), (8, 13, "ANIMAL")]}),
    
    ("Dog sleeps on the carpet", {"entities": [(0, 3, "ANIMAL")]}),
    ("The cat is very playful", {"entities": [(4, 7, "ANIMAL")]}),
    ("Chicken runs fast", {"entities": [(0, 7, "ANIMAL")]}),
    ("A butterfly is flying around", {"entities": [(2, 11, "ANIMAL")]}),
    ("An elephant sprays water", {"entities": [(3, 11, "ANIMAL")]}),
    ("The horse neighs loudly", {"entities": [(4, 9, "ANIMAL")]}),
    ("Spider is crawling on the floor", {"entities": [(0, 6, "ANIMAL")]}),
    ("Squirrel jumps from branch to branch", {"entities": [(0, 7, "ANIMAL")]}),
    ("I love the dog in that picture", {"entities": [(11, 14, "ANIMAL")]}),
    ("The cat sleeps peacefully", {"entities": [(4, 7, "ANIMAL")]}),

    ("There is a cow in this picture", {"entities": [(11, 14, "ANIMAL")]}),
    ("A dog can be seen in the photo", {"entities": [(2, 5, "ANIMAL")]}),
    ("The cat is shown in the image", {"entities": [(4, 7, "ANIMAL")]}),
    ("This photo features a chicken", {"entities": [(21, 28, "ANIMAL")]}),
    ("Look at the butterfly in the picture", {"entities": [(12, 21, "ANIMAL")]}),
    ("An elephant appears in the photograph", {"entities": [(3, 11, "ANIMAL")]}),
    ("The horse is visible in this image", {"entities": [(4, 9, "ANIMAL")]}),
    ("A spider is depicted on the photo", {"entities": [(2, 8, "ANIMAL")]}),
    ("Squirrel can be seen climbing a tree", {"entities": [(0, 7, "ANIMAL")]}),
    ("This picture shows a cat and a dog", {"entities": [(19, 22, "ANIMAL"), (27, 30, "ANIMAL")]}),
     ("A sheep is grazing in the meadow", {"entities": [(2, 7, "ANIMAL")]}),
    ("The picture shows a sheep", {"entities": [(19, 24, "ANIMAL")]}),
    ("Sheep are running across the field", {"entities": [(0, 5, "ANIMAL")]}),
    ("I saw a sheep near the barn", {"entities": [(8, 13, "ANIMAL")]}),
    ("Look at the sheep eating grass", {"entities": [(12, 17, "ANIMAL")]}),
]